### ISSUE TITLE
Layout: duplicando o firstname

### ISSUE THREAD

**Issue by diasalvesj** [MCobias/talkto#20]
Na parte de frente do bloco, após atribuir o papel ao usuário na disciplina Moodle, aparece o nome (firstname) duplicado....sendo que deveria puxar o firstname e o lastname ou o primeiro e último nome (igual no Projeção).

**Comment by MCobias** [comment]
Anteriormente fazia-se necessário uma adequação no nome, pois utilizava-se o firstname para o nome completo do perfil do papel. Pegava-se a primeira string e a última para encurtar o nome no perfil.
